version: "3.9"

services:
  regression:
    build:
      context: .   # если docker-compose.yml лежит рядом с Dockerfile
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    volumes:
      - ./:/usr/workspace
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}
